version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - mynetwork
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 172.17.0.1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper



  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - mynetwork
  producer:
      container_name: producer
      ports:
        - 5004:5004
      depends_on:
        - kafka
        - zookeeper
        - mongo
      build: ./services/producer
      networks:
        - mynetwork
      links:
        - mongo
        - kafka
  consumer:
      container_name: consumer1
      command: sh -c "sleep 30 && python consumer.py 1"
      ports:
        - 5001:5001
      depends_on:
        - kafka
        - zookeeper
        - mongo
        - producer
      build: ./services/consumer
      networks:
        - mynetwork
      links:
        - kafka
  consumer2:
      container_name: consumer2
      command: sh -c "sleep 30 && python consumer.py 2"
      ports:
        - 5002:5002
      depends_on:
        - kafka
        - zookeeper
        - mongo
        - producer
      build: ./services/consumer
      networks:
        - mynetwork
      links:
        - kafka
  consumer3:
      container_name: consumer3
      command: sh -c "sleep 30 && python consumer.py 3"
      ports:
        - 5003:5003
      depends_on:
        - kafka
        - zookeeper
        - mongo
        - producer
      build: ./services/consumer
      networks:
        - mynetwork
      links:
        - kafka
networks:
  mynetwork:
    driver: bridge
